const mlink2 = document.createElement('a');
disText2 = document.createTextNode("Fibonacci");
mlink2.appendChild(disText2);
mlink2.title = "Fibonacci";
mlink2.href = "https://66nihaal44.github.io/testedSite/fibonacci";
document.getElementById("menu").appendChild(mlink2);
const mlink3 = document.createElement('a');
disText3 = document.createTextNode("Quiz");
mlink3.appendChild(disText3);
mlink3.title = "Quiz";
mlink3.href = "https://66nihaal44.github.io/testedSite/quiz";
document.getElementById("menu").appendChild(mlink3);
