const mlink1 = document.createElement('a');
const disText1 = document.createTextNode("Main Page");
mlink1.appendChild(disText1);
mlink1.title = "Main Page";
mlink1.href = "https://66nihaal44.github.io/testedSite/";
document.getElementByClass("menu").appendChild(mlink1);
const mlink2 = document.createElement('a');
const disText2 = document.createTextNode("Second Page");
mlink2.appendChild(disText2);
mlink2.title = "Second Page";
mlink2.href = "https://66nihaal44.github.io/testedSite/secondpage";
document.getElementByClass("menu").appendChild(mlink2);
const mlink3 = document.createElement('a');
const disText3 = document.createTextNode("Quiz");
mlink3.appendChild(disText3);
mlink3.title = "Quiz";
mlink3.href = "https://66nihaal44.github.io/testedSite/quiz";
document.getElementByClass("menu").appendChild(mlink3);
